name: Deploy Blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Build Project
      run: |
        make

    - name: Generate Site
      run: |
        mkdir -p _site
        ./blog-generator _site

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        full_commit_message: ${{ github.event.head_commit.message }}
        user_name: 'gh-pages'
        user_email: 'github-actions[bot]@users.noreply.github.com'
